### ISSUE TITLE
Division by zero in SingleTopReconstruction

### ISSUE THREAD

**Issue by marco-link** [WbWbX/nanoAOD-tools#14]
The `2022-03-25_v2` campaign had some failed jobs with this error message:
```
== CMSSW: Traceback (most recent call last):
== CMSSW:   File "ST.py", line 453, in <module>
== CMSSW:     p.run()
== CMSSW:   File "/srv/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 234, in run
== CMSSW:     eventRange=eventRange, maxEvents=self.maxEntries
== CMSSW:   File "/srv/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/eventloop.py", line 78, in eventLoop
== CMSSW:     ret = m.analyze(e)
== CMSSW:   File "/srv/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/modules/SingleTopReconstruction.py", line 148, in analyze
== CMSSW:     cosWhel = leptonInWbosonRestframe.Vect().Dot(topInWbosonRestframe.Vect())/leptonInWbosonRestframe.Vect().Mag()/topInWbosonRestframe.Vect().Mag()
== CMSSW: ZeroDivisionError: float division by zero
```

**Comment by defranchis** [comment]
@matt-komm what would be the best way to fix this? Set it to some standard value like -2? We could also comment out some variables that we will probably not need for this analysis

@marco-link how many jobs failed with this error?

**Comment by marco-link** [comment]
8 out of 21k jobs failed with this error.

**Comment by matt-komm** [comment]
how do this occur? if one of the vectors leptonInWbosonRestframe or topInWbosonRestframe is 0 then this is a different problem

**Comment by defranchis** [comment]
I would assume that this is what’s happening. Is the lepton mass set to zero?

**Comment by matt-komm** [comment]
this is the p3 vector - should not depend on the mass

**Comment by defranchis** [comment]
> this is the p3 vector - should not depend on the mass

ah sorry, indeed. Then yes, it looks one of the vectors is zero. How would you propose to solve this? Since this probably only involves a bunch of events (and most likely we don't need this variable) I would propose setting the cos to e.g. -2

**Comment by defranchis** [comment]
proposed solution in https://github.com/WbWbX/nanoAOD-tools/pull/16

**Comment by defranchis** [comment]
Solved in https://github.com/WbWbX/nanoAOD-tools/pull/16
