### ISSUE TITLE
Value Error: average PU weight more than 5 standard deviations away from 1

### ISSUE THREAD

**Issue by marco-link** [WbWbX/nanoAOD-tools#15]
The `2022-03-25_v2` campaign had [one failed job](https://cmsweb.cern.ch:8443/scheddmon/0120/mlink/220325_181327:mlink_crab_TTToHadronic_TuneCP5_13TeV-powheg-pythia8/job_out.76.11.txt) with this error message:
```
== CMSSW: Processed 9809 preselected entries from dcap://cmsdcap-kit.gridka.de:22125/pnfs/gridka.de/cms/disk-only/store/user/mlink/WbChargeReco/2022-03-01_v6/mc_2017/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/WbChargeReco_mc_2017_2022-03-01_v6/220301_120731/0000/nanox_167.root (12000 entries). Finally selected 2 entries
== CMSSW: Done ./nanox_167_Skim.root
== CMSSW: Traceback (most recent call last):
== CMSSW:   File "ST.py", line 453, in <module>
== CMSSW:     p.run()
== CMSSW:   File "/srv/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 253, in run
== CMSSW:     m.endJob()
== CMSSW:   File "/srv/CMSSW_11_1_7/python/PhysicsTools/NanoAODTools/modules/PUWeightProducer.py", line 74, in endJob
== CMSSW:     raise ValueError('average PU weight more than 5 standard deviations away from 1')
== CMSSW: ValueError: average PU weight more than 5 standard deviations away from 1
```

**Comment by defranchis** [comment]
@matt-komm is this really necessary to keep this check that we discussed together? This happened because only 2 entries were selected (which is not surprising for backgrounds like ttbar hadronic). I would comment this out, in the end we will check the data/MC nPV distributions

**Comment by defranchis** [comment]
@matt-komm I propose turning this from a ValueError into a Warning. If there are no objections I will go with this solution

**Comment by defranchis** [comment]
proposed solution in https://github.com/WbWbX/nanoAOD-tools/pull/16

**Comment by defranchis** [comment]
Solved in https://github.com/WbWbX/nanoAOD-tools/pull/16
replaced with warning (will have to check PU weights at analysis level)
